image: python:3.8
stages:
  - deploy


variables:
  REGION: $AWS_REGION
  STACK_NAME: $STACK_NAME
  S3_BUCKET: $S3_BUCKET
  TEMPLATE: $TEMPLATE

Dev:
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam deploy --template-file ${TEMPLATE} --stack-name ${STACK_NAME} --s3-bucket ${S3_BUCKET} --capabilities CAPABILITY_IAM --region ${REGION}
  environment: dev