image: python:3.8
stages:
  - deploy


variables:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}


Dev:
  stage: deploy
  before_script:
    - pip3 install boto3
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - python CFNStackCreation.py
  environment: dev